[package]
name = "aws_crawl"
version = "0.1.0"
authors = ["Kim Jin Su <item4_hun@hotmail.com>"]

[dependencies]
reqwest = "^0.9.5"
env_logger = "^0.6.0"
encoding = "0.2"
scraper = "0.8.1"
ego-tree = "0.5.0"
regex = "1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0"
clap = "2.32.0"