[package]
name = "weather_crawl"
version = "0.1.0"
authors = ["Kim Jin Su <item4_hun@hotmail.com>"]
edition = "2018"

[dependencies]
rust_decimal = { version = "^1.7.0", features = ["serde-float"] }
tokio = { version = "^0.2.22", features = ["macros"] }
reqwest = "^0.10.8"
env_logger = "^0.7.1"
encoding = "^0.2.33"
scraper = "^0.12.0"
ego-tree = "^0.6.2"
regex = "^1.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "^1.0.57"
clap = "^2.33.3"
